name: Scan container image

permissions:
  checks: write
  contents: read
  pull-requests: write

on: 
  workflow_dispatch:
  pull_request_target:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build the Container image
        run: sudo sh gradlew jibDockerBuild
      - uses: anchore/scan-action@v3
        id: scan
        with:
          image: "devsecops/vulnerableapp:latest"
          fail-build: false
          acs-report-enable: true
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}